import type { Metadata } from "next";
import "pretendard/dist/web/variable/pretendardvariable-dynamic-subset.css";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "formbwa",
  description: "Generated by formbwa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* 순수 흑백을 쓰지 않는다 — 뉴트럴은 전부 민트 색상환으로 틴트 (globals.css @theme) */}
      <body className="bg-canvas text-ink font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
