/**
 * 토큰(src/*.ts) → theme.css (Tailwind v4 @theme static) 생성기.
 * 실행: pnpm --filter @repo/design-tokens gen
 * 결과 theme.css는 커밋한다 (결정적, Tailwind 빌드순서 의존 제거).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { colors } from "../src/colors";
import { spacing } from "../src/spacing";
import { fontFamily, fontSize } from "../src/typography";
import { radius } from "../src/radius";

const lines: string[] = [];

// 폰트패밀리
for (const [key, value] of Object.entries(fontFamily)) {
  lines.push(`  --font-${key}: ${value};`);
}
lines.push("");

// 색 (중첩 객체는 --color-<key>-<sub>, 평면은 --color-<key>)
for (const [key, value] of Object.entries(colors)) {
  if (typeof value === "object") {
    for (const [sub, v] of Object.entries(value)) {
      lines.push(`  --color-${key}-${sub}: ${v};`);
    }
  } else {
    lines.push(`  --color-${key}: ${value};`);
  }
}
lines.push("");

// 간격
for (const [key, value] of Object.entries(spacing)) {
  lines.push(`  --spacing-${key}: ${value};`);
}
lines.push("");

// 타이포 (크기 + 라인하이트)
for (const [key, { size, lineHeight }] of Object.entries(fontSize)) {
  lines.push(`  --text-${key}: ${size};`);
  lines.push(`  --text-${key}--line-height: ${lineHeight};`);
}
lines.push("");

// radius
for (const [key, value] of Object.entries(radius)) {
  lines.push(`  --radius-${key}: ${value};`);
}

const css = `/* GENERATED by @repo/design-tokens — 직접 수정 금지.
   토큰은 src/*.ts에서 고치고 \`pnpm --filter @repo/design-tokens gen\` 실행.
   static: 미사용 토큰도 :root에 방출 (토큰 문서가 읽는다). */
@theme static {
${lines.join("\n")}
}
`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "theme.css");
writeFileSync(outPath, css);
console.log(`✔ theme.css 생성: ${outPath}`);
